package jpa.modelEntities;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import java.io.Serializable;
import java.util.Objects;

/*
  ON MY OPINION THIS ENTITY IS OBSOLETE AND WAS GENERATED BY JPA BUDDY, SEE COMPANY MANY-TO-MANY
 */
@Embeddable
public class CompanypartnershipId implements Serializable {
    private static final long serialVersionUID = 1872106362401359751L;
    @Column(name = "companyid", nullable = false)
    private Integer companyid;

    @Column(name = "companypartnerid", nullable = false)
    private Integer companypartnerid;

    public Integer getCompanyid() {
        return companyid;
    }

    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }

    public Integer getCompanypartnerid() {
        return companypartnerid;
    }

    public void setCompanypartnerid(Integer companypartnerid) {
        this.companypartnerid = companypartnerid;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        CompanypartnershipId entity = (CompanypartnershipId) o;
        return Objects.equals(this.companyid, entity.companyid) &&
                Objects.equals(this.companypartnerid, entity.companypartnerid);
    }

    @Override
    public int hashCode() {
        return Objects.hash(companyid, companypartnerid);
    }

}